services:
  postgres:
    image: postgres:14.6
    restart: always
    container_name: crypto-diary-db
    environment:
      POSTGRES_DB: crypto-diary-db
      POSTGRES_USER: designer
      POSTGRES_PASSWORD: true
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
