# gin_mode: release

logger:
  log_level: debug
  file_name: "logs/lumberjack.log"
  is_console_log_enable: true
  is_file_log_enable: true
  is_compress: false

server:
  socket: 0.0.0.0:8081
  shutdown_timeout: 15s
  read_timeout: 15s
  write_timeout: 15s

auth:
  issuer: crypto-diary.space
  refresh_token_lifetime: 168h
  refresh_token_secret: 7PFUSSxFjeVkbxqAn5ktapVE2PvbQgTgzsrztktawFbYK2TubTkp4JvgjpHP3Taa
  access_token_lifetime: 15m
  access_token_secret: KycVkWHPDygdJFgerbHjr7v7erWF2NA7uxEkgTaeQLgqS2939XjmcVJUQfKEApkS

session_storage:
  socket: session:6379
  password: ""
  database: 0

password_secret: pWu2EnUd3yqyP9mfK7uaqWdNFjWTeKEvVxFCLcxE2hhJuwY9jKRb2ZwHztjC3LmL

storage:
  username: designer
  password: designer
  socket: storage:5432
  database: crypto_diary
  conn_attempts: 15
  conn_timeout: 3s
  pool_size: 99 # one for attach
