log_level: info
server:
  socket: 0.0.0.0:8080
  shutdown_timeout: 0 # in seconds
storage:
  username: designer
  password: designer
  host: postgres
  port: 5432
  database: crypto-diary
  conn_attempts: 10
  conn_timeout: 1 # in seconds
  pool_size: 1
