log_level: debug
# gin_mode: release

server:
  socket: 0.0.0.0:8080
  shutdown_timeout: 3s
  read_timeout: 15s
  write_timeout: 15s

auth:
  issuer: crypto-diary.com # e.g.
  refresh_token_lifetime: 168h
  refresh_token_secret: TnFVnbXaqpgmZhpbNcWJunp2CZNkmRLtxxdzkijvoqMtk7LpS2xp7pWitTDRFkXtZXKS22Es
  access_token_lifetime: 15m
  access_token_secret: fWoWCe9MfDihrPr4j7FH5dgy33kXdsRYVj9oWVHYQFynUWg9FSiRc3jMp9CtEJjXXYxAvrVb

session_storage:
  socket: session:6379
  password: ""
  database: 0

password_secret: 47x7o3yFukFjWQ94Z9qFeQhVtXy7spzYZiFu5eLsU72uxUbSo35bu2j9tDTEcAZaAnWcnwZe

storage:
  username: designer
  password: designer
  socket: storage:5432
  database: crypto_diary
  conn_attempts: 10
  conn_timeout: 3s
  pool_size: 1
